---
### Backend ###
backend_src_dir: '{{ deploy_src_dir }}/api'
backend_repo: ''
backend_repo_branch: 'master'


### Django ###
django_dir: '{{ backend_src_dir }}/project'
django_app_name: 'django_app'
django_wsgi_file: '{{ django_dir }}/{{ django_app_name }}/wsgi.py'
django_settings: '{{ django_app_name }}.settings'
django_static_url: '/static'
django_static_root: '{{ django_dir }}/collected_static'
django_media_url: '/media'
django_media_root: '{{ django_dir }}/media'
django_local_settings_file: '{{ django_dir }}/local_settings.py'
django_fixtures: [] # Path to fixture file. Example: '{{ django_dir }}/fixtures/initial.json


### Tornado ###
tornado_host: 127.0.0.1
tornado_port: 9000


### Local settings ###
debug: False
django_settings_module: '{{ django_app_name }}.settings'
secret_key: '{{ vaulted_secret_key }}'

database_host: 'localhost'
database_port: '{{ postgresql_port }}'
database_name: '{{ vaulted_database_name }}'
database_user: '{{ vaulted_database_user }}'
database_password: '{{ vaulted_database_password }}'

cache_default_location: 'redis://{{ redis_bind }}:{{ redis_port }}/1'
cache_celery_location: 'redis://{{ redis_bind }}:{{ redis_port }}/2'
cache_celery_result_location: 'redis://{{ redis_bind }}:{{ redis_port }}/3'


### Python ###
python_versions:
  - 3.5
python_install: []
python_virtualenvs:
  - path: '{{ virtualenv_dir }}'
    python: python3.5


### PIP requirements ###
pip_requirements:
  - '{{ django_dir }}/requirements.txt'


### Virtualenv ###
virtualenv_dir: '{{ deploy_dir }}/venv'
