# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170403_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.png', upload_to='images/'),
        ),
    ]
