# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20170404_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
